---
#- hosts: '{{ target }}'
- hosts: all
  become: true
  #become_method: sudo
  tasks:
  - name: "Update cache & Full system update"
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true